version: "3"

name: grafana

services:
  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - "grafana:/var/lib/grafana"
    env_file:
      - "stack.env"
    networks:
      - public
      - monitoring
      - collector
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitor.spearcrow.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    restart: always

  netdata:
    image: netdata/netdata:v1.38
    container_name: netdata
    hostname: monitor.spearcrow.com
    ports:
      - 19999:19999
    env_file:
      - stack.env
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      - monitoring
      - collector

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - collector
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    ports:
      - 9093:9093
    networks:
      - collector
      - monitoring

volumes:
  grafana:
  netdataconfig:
  netdatalib:
  netdatacache:
  prometheus_data:

networks:
  collector:
    enable_ipv6: false
  monitoring:
    external: true
  public:
    external: true
